### ISSUE TITLE
Use bugs.ruby-lang.org instead of redmine.ruby-lang.org

### ISSUE THREAD

**Issue by znz** [sunaku/ruby-coroutine-example#1]
Your repository's description includes `https://redmine.ruby-lang.org/issues/2294`, but it is invalid now.
Please use `https://bugs.ruby-lang.org/issues/2294` instead.
See https://github.com/ruby/bugs.ruby-lang.org/issues/68 for more detail.

**Comment by sunaku** [comment]
Fixed, thanks. :+1:
